version: '3.4'

services:      
  sqlserverd:        
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: "mypassword123#"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      
  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "8080:8000" 
      - "9000:9000" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
  sqlserver_data:
